[tool.poetry]
name = "pysanejs"
version = "1.0"
description = "Python client for SaneJS"
authors = ["Raphaël Vinot <raphael@vinot.info>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
mypy = "^0.761"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
